### ISSUE TITLE
Chart PDB does not work on Kubernetes Version <=1.20

### ISSUE THREAD

**Issue by mitchellmaler** [kuberhealthy/kuberhealthy#1000]
**Describe the bug**
Currently the PDB hard codes the api version to policy/v1 which pdb is not part of that before 1.21
https://github.com/kuberhealthy/kuberhealthy/blob/master/deploy/helm/kuberhealthy/templates/poddisruptionbudget.yaml#L3

**Steps To Reproduce**
- Deploy a kubernetes 1.20 cluster
- Deploy kuberheathly with pdb enabled

**Expected behavior**
PDB is deployed

**Versions**
 - Cluster OS: CentOS 7
 - Kubernetes Version: 1.20
 - Kuberhealthy Release or build [e.g. 0.1.5 or 235] 76

**Additional context**
Would recommend allowing to template the PDB version or have two pdb template specific to each version.

**Comment by integrii** [comment]
The latest helm chart should fix this one.
