### ISSUE TITLE
pullSecret support on helm chart

### ISSUE THREAD

**Issue by pragmaticivan** [kuberhealthy/kuberhealthy#1006]
**Describe the feature you would like and why you want it**
Thoughts on supporting `pullSecret` for all the docker images? Docker has rate limiting now and it's something that have been changing over the past few months.

**Comment by jonnydawg** [comment]
I think this would be a great option for to add into the helm chart -- it would only be a few small changes!

Are you assuming a single `imagePullSecret` for all images in this case?

**Comment by pragmaticivan** [comment]
@jonnydawg yes assuming someone will not try to keep one image in dockerhub and the rest on ECR.

I currently made it work by patching the ServiceAccounts and creating a secret.

**Comment by integrii** [comment]
I think we should be careful not to put _too_ many options in the Helm chart.

The Chart has a lot of options already, and it seems like someone can add the `imagePullSecret` for their own `khcheck` resources pretty easily for the server in question within their namespace using [these steps](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-secret-by-providing-credentials-on-the-command-line) from the Kubernetes docs.  

However, setting an `imagePullPolicy` for the kuberhealthy deployment is pretty hard.  Perhaps we can minimize the additions to the helm chart by simply adding an `imagePullPolicy` property to the `kuberhealthy` deployment if specified in the global options.  This would mean that users would need to create the secret themselves outside the chart.

Thoughts?
