### ISSUE TITLE
Connection refused for k8s api

### ISSUE THREAD

**Issue by pragmaticivan** [kuberhealthy/kuberhealthy#1007]
Currently getting this error. Wondering if there's another setup to be aware
```
    "kuberhealthy/pod-restarts": {
      "OK": false,
      "Errors": [
        "Get https://172.20.0.1:443/api/v1/events?fieldSelector=type%3DWarning: dial tcp 172.20.0.1:443: connect: connection refused"
      ],
      "RunDuration": "",
      "Namespace": "kuberhealthy",
      "Node": "",
      "LastRun": "2021-08-20T16:31:28Z",
      "AuthoritativePod": "kuberhealthy-55d8dc7cff-zp8mj",
      "uuid": "d15d798a-385b-4a9c-bcf7-4941dad5e11d"
    },
```

**Comment by jonnydawg** [comment]
Hello @pragmaticivan, could you please provide what Cluster OS, k8s version, and pod-restarts version you are using?

**Comment by pragmaticivan** [comment]
pod-restarts version: kuberhealthy/pod-restarts-check:v2.5.0

Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.17-eks-087e67", GitCommit:"087e67e479962798594218dc6d99923f410c145e", GitTreeState:"clean", BuildDate:"2021-07-31T01:39:55Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**Comment by integrii** [comment]
This seems like a generic 'kubernetes client could not talk to the Kubernetes API' error.  I am not sure Kuberhealthy code could cause this one... Maybe there is a `NetworkPolicy` in place somewhere?
