### ISSUE TITLE
Supporting the function of Setting externalURL by dynamic kuberhealthy pod ip

### ISSUE THREAD

**Issue by Hungrylion2019** [kuberhealthy/kuberhealthy#1018]
**Describe the feature you would like and why you want it**
### Background
When  the kuberhealthy is working in the cluster , my cluster is short of the component such as CoreDns service to parse the  KHExternalReportingURL "http://kuberhealthy.kuberhealthy.svc.cluster.local/externalCheckStatus". 
### Result
I find the checker failed to upload the data to kuberhealthy ,because the KHExternalReportingURL is unavailable.
### How I deal with 
1. I get the kuberhealthy service ip
2. Edit the kuberhealthy deployment in the cluster
3.  add the kuberhealthy deployment's pod containter env "KH_EXTERNAL_REPORTING_URL"= "http://$(ServiceIP)/externalCheckStatus"
4. This work fine. Checker can normaly upload the data to kuberhealthy endpoint.
### What's my problem for this resolution
1. My cluster deploy the kuberhealthy by  Gitlab CICD to kustomize advanced kuberhealthy.yaml
2. Now ,I can't get kuberhealthy service ip until the kuberhealthy has been deployed into the cluster by our gitlab CICD instead of setting the yaml in advance.
3. Although I can enter the cluster and edit the kuberhealthy deployment ，this will result in the difference  between our cluster's actual configuration and our gitlab repository. This is not what we expected.
### What's my suggestion and  what I am expected the kuberhealthy to do
1. modfy the kuberhealthy deployment yaml to add Pod env 
```
        - name: KH_EXTERNAL_REPORTING_URL
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
```
2.  modify the code of kuberhealthy to parse externalCheckURL to support get pod ip and assemble it to the valid externalCheckURL，such as：
```
	// set env variables into config if specified. otherwise set external check URL to default
	externalCheckURL, err := getEnvVar(KHExternalReportingURL)
	if err != nil {
		if len(podNamespace) == 0 {
			return errors.New("KH_EXTERNAL_REPORTING_URL environment variable not set and POD_NAMESPACE environment variable was blank.  Could not determine Kuberhealthy callback URL.")
		}
		log.Infoln("KH_EXTERNAL_REPORTING_URL environment variable not set, using default value")
		externalCheckURL = "http://kuberhealthy." + podNamespace + ".svc.cluster.local/externalCheckStatus"
	}
//----------------------------------
      // the code I modified
      // Default kuberhealthy port
          var DefaultPodPort = "8080"
	r, err := url.Parse(externalCheckURL)
	if err != nil {
		log.Errorln("parse url ", externalCheckURL, "failed!")
	}
	log.Infoln("the parse externalCheckURL is ", externalCheckURL)

	// Prepend the url with a HTTP protocol.
	if !strings.HasPrefix(externalCheckURL, "http://") {
		externalCheckURL = "http://" + externalCheckURL
	}
	if len(r.Port()) == 0 {
		kuberhealthyPodPort, err := getEnvVar("POD_PORT")
		if err != nil {
			kuberhealthyPodPort = DefaultPodPort
		}
		externalCheckURL = externalCheckURL + ":" + kuberhealthyPodPort
	}
	// Prepend the url with a /externalCheckStatus path.
	if !strings.HasSuffix(externalCheckURL, "/externalCheckStatus") {
		externalCheckURL = externalCheckURL + "/externalCheckStatus"
	}
/----------------------------------
	cfg.ExternalCheckReportingURL = externalCheckURL
	log.Infoln("External check reporting URL set to:", cfg.ExternalCheckReportingURL)
```
### What we can get by this modification 
1. Supporting to kuberhealthy and checker to work fine into the cluster which is lack of the CoreDns or other dns tool.
2.  Supporting the gitlab to complete task to keep the same with cluster and gitlab repository by modify the yaml instead of the manual manipulation

**Comment by integrii** [comment]
It sounds like the core ask here is that you would like Kuberhealthy to support clusters that do not have a working `cluster.local` DNS zone.  Is that a good summary of the feature request?
