### ISSUE TITLE
Strengthen the function of pre-test to kuberhealthy endpoint for checker

### ISSUE THREAD

**Issue by Hungrylion2019** [kuberhealthy/kuberhealthy#1019]
**Describe the feature you would like and why you want it**
When my checker pod failed to report to kuberhealthy endpoint after having worked successfully，I tracked the log from our elasiticsearch plattform and the log confused me.

log:
```
2022-01-10T05:38:17.000+08:00 Kuberhealthy endpoint: http://kuberhealthy.kuberhealthy.svc.cluster.local/externalCheckStatus is ready. Proceeding to run check.
```
Actually,  I found the issue was caused beacuse my cluster is short of the CoreDns service to parse "http://kuberhealthy.kuberhealthy.svc.cluster.local" to specific ip address.

 But the kuberhealthy endpoint pre-test is successful ,this is strange.

I started to review the code, and I found the unexpected code design.
```
func waitForKuberhealthyEndpointReady(ctx context.Context, kuberhealthyEndpoint string) chan error {

	doneChan := make(chan error, 1)

	for {
		select {
		case <-ctx.Done():
			doneChan <- errors.New("context cancelled waiting for Kuberhealthy endpoint to be ready")
			return doneChan
		default:
		}
//--------------------------------
// only create NewRequest ,not to DO(request).
// There is no doubt that this reulst is still successful even though the kuberhealthy endpoint is unaccessible.
		_, err := http.NewRequest("GET", kuberhealthyEndpoint, nil)
		if err == nil {
			log.Debugln(kuberhealthyEndpoint, "is ready.")
			doneChan <- nil
			return doneChan
		} else {
			log.Debugln(kuberhealthyEndpoint, "is not ready yet..."+err.Error())
		}
		time.Sleep(time.Second * 3)
	}
//------------------------------------
}
```
-  **As you can see, thie code want to make a pre-test kuberhealthy endpoint, but it only  assemble requset and  not "Do(request)" to test if the endpoint is accessible.**
- **If the piece of code is enough ,the checker  should quit between  the log "Waiting for node to become ready before starting check." and "Starting check" . This can let developer understand  where is the bug right now .**

**Additional context**
I had already mentioned this problem in the final comment in '1015' issue.
https://github.com/kuberhealthy/kuberhealthy/issues/1015

**Comment by integrii** [comment]
Addressed [here](https://github.com/kuberhealthy/kuberhealthy/issues/1015#issuecomment-1040732961)

**Comment by Hungrylion2019** [comment]
- I see your point. But what 's the code’s purpose ？ 
-  Only to create NewRequest not do it，this will be successful forever. I don't see the point of this code.
