### ISSUE TITLE
securityContext should support providing all possible values at container level

### ISSUE THREAD

**Issue by AshutoshNirkhe** [kuberhealthy/kuberhealthy#1025]
**Describe the bug**
Currently the securityContext from values.yaml (https://github.com/kuberhealthy/kuberhealthy/blob/v2.7.0/deploy/helm/kuberhealthy/values.yaml#L89) appears to allow all possible security settings at container level. But not sure if they all really get picked up by kuberhealthy backend pods as well as kuberhealthy checks. 
For example, for Kuberhealthy deployment its picking only few pre-defined options runAsNonRoot, runAsNonRoot and allowPrivilegeEscalation. What if I want to add readOnlyRootFilesystem: true ?(https://github.com/kuberhealthy/kuberhealthy/blob/v2.7.0/deploy/helm/kuberhealthy/templates/deployment.yaml#L84)

Also not sure if/how below KH checks (that we are using internally) make use of securityContext settings,
1] DNS check - https://github.com/kuberhealthy/kuberhealthy/blob/v2.7.0/cmd/dns-resolution-check/internalDNSStatusCheck.yaml#L10
2] Deployment check - https://github.com/kuberhealthy/kuberhealthy/blob/v2.7.0/cmd/deployment-check/deployment-check.yaml#L11

**Steps To Reproduce**
1] I tested adding readOnlyRootFilesystem: true manually to securityContext in deployment and Kuberhealthy pods came up fine, so it's definitely supported, but we don't have a way to achieve this via helm chart.
$ kubectl get pod kuberhealthy-7f755c7574-fknx6 -n synthetic -o=jsonpath='{.spec.containers[].securityContext}'
{"allowPrivilegeEscalation":false,"readOnlyRootFilesystem":true,"runAsNonRoot":true,"runAsUser":999}

**Expected behavior**
Ideally deployment-check.yaml should support all possible securityContext settings (may be by just accepting all securityContext as   .values.securityContext instead of retrieving child elements). 

**Screenshots**
If applicable, add screenshots to help explain your problem.  You can paste images into github and they will upload automatically.

**Versions**
 - Cluster OS: Linux Ubuntu (18.04.1-Ubuntu)
 - Kubernetes Version: 1.21.7
 - Kuberhealthy Release : v2.7.0
**Additional context**

**Comment by integrii** [comment]
Makes sense.  We should definitely include the security settings in all of our `khcheck` specs deployed with the helm chart.

As a workaround, you could use `helm template` and then add the security settings to the `podTemplate` section.

So basically, we need to go through all the specs in the helm chart and ensure that they implement all the `securityContext` options...

**Comment by AshutoshNirkhe** [comment]
> Makes sense. We should definitely include the security settings in all of our `khcheck` specs deployed with the helm chart.
> 
> As a workaround, you could use `helm template` and then add the security settings to the `podTemplate` section.
> 
> So basically, we need to go through all the specs in the helm chart and ensure that they implement all the `securityContext` options...

Yeah, the actual securityContext settings need to be added to KH deployment itself and built-in check's container spec.
