### ISSUE TITLE
Commit need signing off

### ISSUE THREAD

**Issue by hans-d** [kuberhealthy/kuberhealthy#1027]
(https://github.com/kuberhealthy/kuberhealthy/pull/1026)

> There is one commit incorrectly signed off. This means that the author of this commit failed to include a Signed-off-by line in the commit message.

There is no reference in the CONTRIBUTING.md re signing off the commits, eg what does it signify and why is it required.

**Comment by integrii** [comment]
This is due to the DCO bot requiring your `git` commits to be signed.  This is required by the CNCF to ensure that the committer's name can not be spoofed.

![image](https://user-images.githubusercontent.com/98695/155187830-752f36c3-38ce-4f55-ab96-15748811cf5c.png)

If you hit details on this, [it will tell you how to sign your commits](https://github.com/kuberhealthy/kuberhealthy/pull/1026/checks?check_run_id=5271756002).

**Comment by hans-d** [comment]
Hi, the dco bot tells me to "sign off" (lowercase -s), not to Sign (capital -S). Sign is with a gpg key and has some level of authentication (and gices the green verified). Sign off is just some text added to a commit text, which can be easily spoofed. 

Neither is mentioned in the CONTRIBUTING.md, nor see i something mentioned in the CNCF CLA regarding this. The DCO details only tells me how to do it, not why.

Quite happy to sign a CLA, but would like to know up front what i'm signing off for.

**Comment by integrii** [comment]
It is interesting that you don't use a capital `S` when signing commits and instead use a lowercase "sign off" that basically only puts something in the commit message.  I can tell you that [we had to enable this as per the CNCF guidelines](https://github.com/cncf/toc/issues/627), but I can't really tell you what the exact legal pretense for it is.  It does look like [there are some clues on developercertificate.org](https://developercertificate.org).

It was either this or a CLA bot.  I was originally preferring the CLA bot, but ended up having trouble getting it enabled and thus went with the DCO bot.

I will add this to the CONTRIBUTING.md file.  It looks like that file still mentions the CLA agreement and not the DCO bot.
