### ISSUE TITLE
Reporting error when checker completed check successfully

### ISSUE THREAD

**Issue by Hungrylion2019** [kuberhealthy/kuberhealthy#1047]
**Describe the bug**
When I found the error msg " timed out waiting for checker pod to report in", I started looking for where is this bug.
1. Firstly, I got the checker pod in the cluster and wanted to review the checker pod status.
2. I discovered that the checker pod  did not exist.
3. I review the checker log from our Kibana platform and I found that checker reported successfully.
4. Then I review the kuberhealthy log，and I noticed that the reason why the kuberhealthy  report error msg " timed out waiting for checker pod to report in" was that it didn‘t see that checker pod updated .
5. This confused me why checker had completed check successfully and the kuberhealthy didn‘t see that checker pod updated ,what's more，why the checker pod was deleted immediately after completed check but my yaml config set ”maxCompletedPodCount: 4“
6. Then I saw the description from k8s doc:
```
The control plane cleans up terminated Pods (with a phase of Succeeded or Failed), when the number of Pods exceeds the configured threshold (determined by terminated-pod-gc-threshold in the kube-controller-manager). This avoids a resource leak as Pods are created and terminated over time.
``` 
7. That solved my puzzle, my checker pod was deleted by kube-controller-manager because of the lower value of the terminated-pod-gc-threshold.

8. But I thought kuberhealthy should  block the gc action  by kube-controller-manager,otherwise ,this will result in the unexpected error.

ps: I thought that if we set  "maxCompletedPodCount: 0" can lead to the same phenomenon.
@integrii

**Comment by Hungrylion2019** [comment]
1. I know the kuberhealthy how to reaper checker pod. 
2. My question is that the pods maybe be gc by the kube-controller-manager, this will lead to the unexpected error.
3. I have solved this question in my real cluster.

**Comment by nannu-krish** [comment]
Could you please let us know how you fixed it?

**Comment by Hungrylion2019** [comment]
> @Hungrylion2019 Could you please let us know how you fixed it? It would help me and a lot of people facing the same issue

I have added a finalizer mechanism to the checker pod to ensure that the checker data is successfully uploaded before it is garbage collected. This will achieve the desired effect without modifying the terminated-pod-gc-threshold in KCM.
