### ISSUE TITLE
add namespace selector for Kuberhealthy checks

### ISSUE THREAD

**Issue by M0roSan** [kuberhealthy/kuberhealthy#1048]
**Describe the feature you would like and why you want it**
I would like to specify multiple namespaces and/or with label selector for pod status and pod restart checker. 

as kubernetes admin, as much as I'm interested in running the check for all namespaces, it includes service team namespaces that I have no ownership on. 
Currently, I have to define each check per namespace for system related namespaces. It's static and duplicate workloads. If I can at least select multiple namespaces in the single check like `POD_NAMESPACES: "kube-system,another-system,another"`, it would be great. Moreover, if I can do label selector like `POD_NAMESPACES_SELECTORS: "system=true,key=value"` to choose dynamically at start up time, I don't have to add a new system namespace to this check every time.

**Comment by Hungrylion2019** [comment]
Currently, checker can run in multiple namespaces by setting checker yaml different namespace,but you should apply the yaml in the cluster for one time every time you change the namespace of checker yaml.

**Comment by M0roSan** [comment]
That’s what I’m doing today and I also have to deploy role, role binding and service account for each namespace. In addition, I have to set up monitoring and alerting. I would love to consolidate it into single check with deploying single check with multiple namespaces and cluster role.

**Comment by Hungrylion2019** [comment]
I got your idea,maybe you can refer to our application scenario.
- our cluster put all checker into the same namespace, we think that it's not necessary for checker to run in the different namespace.
- Because the single namespace can still detect hidden dangers,besides,we can manage the total quota and prevent the overflow of all checker resource in the same namespace.
- Based on this rule, it is easier for administrators to focus only on what inspectors report and not on other configuration management

**Comment by integrii** [comment]
I think namespace selectors would be a good addition to our Kuberhealthy checks.  Because of the highly customizable nature of a Kuberhealthy check, this would need implemented on every check.  I am happy to leave this as an open feature request here.  Do you mind if I rename the issue to something simpler such as `add namespace selector for Kuberhealthy checks`?

Also, if you are using Kuberhealthy at Splunk, we would love to have you added to the [adopters list](https://github.com/kuberhealthy/kuberhealthy/blob/master/docs/KUBERHEALTHY_ADOPTERS.md)!

**Comment by M0roSan** [comment]
@integrii you can rename the title of the issue.

I'm asking committee whether we can add Splunk to the adopters list.  hold on tight :) thanks for great work and making this as OSS!

**Comment by integrii** [comment]
Awesome!  Hopefully that is approved and such. We need a certain number of companies adopting Kuberhealthy to promote to the next level within the CNCF.

**Comment by M0roSan** [comment]
for context,
>our cluster put all checker into the same namespace, we think that it's not necessary for checker to run in the different namespace.
 we put checks into different namespaces. and we will be allowing service team to run their own checks in their own namespace. namespace separation on checks allows us to have its ownership and alert separation. having namespace selector is great addition to all kuberhealthy checks and we'd consider implementing the change when the time allows us.

**Comment by integrii** [comment]
Thinking about this a little more... There are some more things that would need considered.  Each `khcheck` resource is considered one check that kuberhealthy manages.  This results in one registered check for clean ups, metrics, and `khstate` resources.  If we are going to change this, we will need to think about what it means for the entirety of the codebase.

- Would creating a `khcheck` that has a `namespaceSelector` cause multiple checks in Kuberhealthy's code to be created?
- Where would `khstate` data for this check go? Currently `khstate` resources only support one check's status at a time.
- How would metrics get created and labeled?
- How would we handle naming collisions in the case that someone made an in-namespace check whose name matched a check in another namespace?
-  Should we create a new `selectorkhcheck` checks to satisfy this constraint?  Each CRD brings a significant code overhead...

**Comment by M0roSan** [comment]
it's approved. we can add Splunk in adopters list.

I've been thinking. 
initially, I just wanted namespace selector for pod status/restart check. I want one single check to check pods in selected namespaces instead of all namespaces or one check per namespace.
for your proposal, we'll add namespace selector for `khcheck` CR. this is useful only if khcheck doesn't require SA and role since we'll have to provision them in each namespace somehow (should be handled outside of kuberhealthy). I still think it's somewhat useful to have namespace selector to provision `khcheck` CR or new CR if and only if we see more demands in it (and tests to run in arbitrary set of namespaces selected by user)

**Comment by Hungrylion2019** [comment]
I thought carefully about the feasibility of the modification.
I thought it only modify these key position of code to achieve our goal.
- khchecker crd----- add new ‘nameselector ’ filed
- kuberhealthy.go/StartChecks func -------Add the action of spliting khcheck with  multiple namespaces
But this change need sto obey some rule.
1. if user dont't set nameselector，it should add its namespace to nameselector，let it become the one of nameselector.
    - It can be compatible with origin khcheck spec.
2. if user set nameselector with multiple namespaces，it should trigger the action to break the khcheck  with multiple namespaces into multiple single khcheck with single khcheck.
    - It can transform the new khcheck into the origin khcheck, because the khstate thinks of {namespace}/{khcheckname} as one khchecke resource. This action will simplify the code modification. 
    - Because we split the new khcheck to origin khcheck ,other code just like 'restart'、'reaper'、‘metrics’、‘khstate’ can stay the same. In theri eyes,they think we dont't change any code.
That's my first thought,there may be some flaws in my idea.
