### ISSUE TITLE
Custom Field with static value in the Report 

### ISSUE THREAD

**Issue by povils** [kuberhealthy/kuberhealthy#1071]
**Describe the feature you would like and why you want it**
Hey, it would be great if we somehow could set the custom fields with static values which would be reported in the health status output. Something like :
```json
    "OK": true,
    "Errors": [],
    "Cluster": "my-cluster-name" // custom field with static value
```

In our case, because we have many clusters and the routing to the correct cluster health endpoint might have bugs, it would be great if we could easily verfify that when we try to access my `/cluster/my-cluster-name/health` is indeed pointing and reporting the correct cluster health. I believe other static information could also be useful, like K8s version 

These custom fields can be as simple as provided as ENV variables to kuberhealhty: Example:
```yaml
KH_STATUS_FIELD_Cluster: "my-cluster-name"
KH_STATUS_FIELD_ClusterVersion: "1.24"
```
If the idea sounds good, I can implement

**Comment by integrii** [comment]
This is an understandable feature request... This would go somewhere in [here](https://github.com/kuberhealthy/kuberhealthy/blob/06c6b9e45ac4186717d825f5e5e6415d1bfb04ff/cmd/kuberhealthy/kuberhealthy.go#L1548)...

**Comment by povils** [comment]
@integrii I am taking this over then :)
