### ISSUE TITLE
DNS Check Daemonset

### ISSUE THREAD

**Issue by mitchellmaler** [kuberhealthy/kuberhealthy#1072]
Hello, is there a way to run the DNS check as a daemonset to check that DNS works across all nodes?

**Comment by integrii** [comment]
I don't think there is currently a check that does this on all nodes, but it could be created.

You would probably do something like:
- (Kuberhealthy spawns your checker pod)
- your check pod pulls a list of nodes in the cluster
- for each node, template out a pod spec with the `nodeName:` property set to that node
- ensure the pod created by the check exits in an Error state if the DNS queries fail (maybe just use a [dnstools container](https://hub.docker.com/r/infoblox/dnstools?)
- one at a time, spawn a pod on each node and ensure it exits propertly
- after all pods are accounted for, send a success message
- if any pod exits unclean, send an error message


Also, you should know that a checker pod registry exists [here](https://github.com/kuberhealthy/kuberhealthy/blob/master/docs/CHECKS_REGISTRY.md)
