### ISSUE TITLE
how to build kuberhealthy from code?

### ISSUE THREAD

**Issue by skaterqiang** [kuberhealthy/kuberhealthy#1080]
how to build kuberhealthy from code?
I searched with google, but I cannot find it.
Could some one help me?

Thanks in advance

**Comment by Hungrylion2019** [comment]
maybe you can  pull the kuberhealthy images to run the container by docker, is this what you want do get?

**Comment by skaterqiang** [comment]
> maybe you can pull the kuberhealthy images to run the container by docker, is this what you want do get?

I am new to kuberhealthy,I want to build the kuberhealthy into some binaries, is there some guide here?

**Comment by fungaren** [comment]
From https://github.com/kuberhealthy/kuberhealthy/blob/master/cmd/kuberhealthy/Makefile

```bash
cd ./cmd/kuberhealthy
go build
./kuberhealthy -h
```
