### ISSUE TITLE
http-content-check be able to set loglevel

### ISSUE THREAD

**Issue by carlossmartini** [kuberhealthy/kuberhealthy#1083]
Currently we're able to set the loglevel for Kuberhealthy, but it looks like the http-content-check does not inherit this setting.  In addition, as far as I could tell, there is not way to set it individually either.

Depending on your configuration this could generate huge amounts of not useful logs 

Would be great if it could either inherit the loglevel set or be able to set it individually or both.

**Comment by h20200051** [comment]
@carlossmartini  I would like to work under this.Kindly assign me
