### ISSUE TITLE
Version 2.7.1 bump

### ISSUE THREAD

**Issue by thebridge90** [kuberhealthy/kuberhealthy#1093]
hello,
Version 2.7.1 is missing what is merged in master.
Could you please create a new release?
I am interested in the addition of https://github.com/kuberhealthy/kuberhealthy/pull/1082

thank you

**Comment by code-haven** [comment]
+1. @integrii would love to see a release with multi-arch images from https://github.com/kuberhealthy/kuberhealthy/pull/1088 :)
