### ISSUE TITLE
Error: no such host

### ISSUE THREAD

**Issue by mohang6770** [kuberhealthy/kuberhealthy#1097]
could someone guide me why i am getting this error and how to resolve it..

time="2022-11-28T17:16:28Z" level=fatal msg="error reporting to kuberhealthy: bad POST request to kuberhealthy status reporting url: Post http://kuberhealthy.kuberhealthy.svc.cluster.local/externalCheckStatus: dial tcp: lookup kuberhealthy.kuberhealthy.svc.cluster.local on 10.96.0.10:53: no such host

**Comment by mohang6770** [comment]
Could someone please help with this..

**Comment by leonchik1976** [comment]
Same here, is there any solution for this?

**Comment by Gourishmanjunathmagganamane** [comment]
same here why i am getting ?
