### ISSUE TITLE
Implement service checker

### ISSUE THREAD

**Issue by lolimjake** [kuberhealthy/kuberhealthy#11]
We should implement a check that verifies services can be created and exposed.

**Comment by integrii** [comment]
Clearing this from the 2.0.0 launch milestone.  This should be implemented as an external check for v2.

**Comment by jonnydawg** [comment]
An external checker for a deployment and service has been created for 2.0.0.

**Comment by jonnydawg** [comment]
#226

**Comment by integrii** [comment]
update: we now have a deployment checker but do not yet have a specific service checker (or ingress checker)
