### ISSUE TITLE
Khcheck http-check expected status code logged as Error

### ISSUE THREAD

**Issue by ramirezag** [kuberhealthy/kuberhealthy#1104]
**Describe the bug**
Khcheck http-check [unexpected status code](https://github.com/kuberhealthy/kuberhealthy/blob/e949431b0c12eb58a44e2a4712c926104e8af9fa/cmd/http-check/main.go#L165) and [expected status code](https://github.com/kuberhealthy/kuberhealthy/blob/e949431b0c12eb58a44e2a4712c926104e8af9fa/cmd/http-check/main.go#L169) are both logged as `Error`. This pollutes our cloud monitoring tool logs with false negatives. 

**Steps To Reproduce**
- [Configure and Deploy](https://github.com/kuberhealthy/kuberhealthy/tree/e949431b0c12eb58a44e2a4712c926104e8af9fa/cmd/http-check#http-get-request-check) http-check
- Check the logs
- You should see `Got a 200 with a GET to http://someurl.xxx` with log level error

**Expected behavior**
[Expected status code](https://github.com/kuberhealthy/kuberhealthy/blob/e949431b0c12eb58a44e2a4712c926104e8af9fa/cmd/http-check/main.go#L169) should be logged as `Info`.

**Screenshots**
Here's how it looks like in our cloud monitoring tool:

<img width="884" alt="Screenshot 2023-01-18 at 16 36 58" src="https://user-images.githubusercontent.com/2081625/213216079-9adf369c-30b5-45a3-8549-50f7c309184a.png">

Note: some info are purposely blocked out

**Versions**
 - Kuberhealthy Release v2.7.1

**Comment by Bharadwajshivam28** [comment]
Hey @integrii @ramirezag  I am new and i will love to work on it

**Comment by Bharadwajshivam28** [comment]
Raised an PR for this issue

**Comment by ramirezag** [comment]
@Bharadwajshivam28, this is already fixed in https://github.com/kuberhealthy/kuberhealthy/pull/1105 and was merged last year. I will close this issue.
