### ISSUE TITLE
Kuberhealthy reports failed test even if the test is successful when sidecar prevents termination

### ISSUE THREAD

**Issue by koalalorenzo** [kuberhealthy/kuberhealthy#1108]
**Describe the bug**

Currently, if you are using istio with Kuberhealthy, the tests are failing and often marked as "Not Ready" and when the tests are done, the only container in the pods is Istio sidecar proxy. This is because the sidecar can't test the liveness of the main container and hangs until timeout is reached.

Even if the test is successful, the container is "Not Ready" and fails because of timeout.

**Steps To Reproduce**

- Install Istio
- Install Kuberhealthy and run any test
- Check the logs of the tests saying that they passed
- check the status for Kuberhealthy and see that it exited with timeout (Pod timeout)

**Expected behaviour**

Tests should be successful when they are successful! 

**Screenshots**

Getting the status from the http interface:

<img width="803" alt="Screenshot 2023-01-26 at 17 31 57" src="https://user-images.githubusercontent.com/33528/214893045-21e7befd-a669-4d9a-af97-b7f1da7b6681.png">

Logs from the test:

```
k logs http-kubeflow-centraldashboard-1674750582
```
<img width="1228" alt="Screenshot 2023-01-26 at 17 31 04" src="https://user-images.githubusercontent.com/33528/214892840-1ab753a2-cf4c-4d90-a5b0-614ce8ee32ff.png">

```
kubctl get pods 
```
<img width="575" alt="Screenshot 2023-01-26 at 17 30 33" src="https://user-images.githubusercontent.com/33528/214892703-8613ccd5-6407-4362-a6c3-be3042558395.png">

**Versions**
 - Cluster OS: GKE Container-Optimized OS from Google
 - Kubernetes Version: v1.23.12-gke.100
 - Kuberhealthy Release or build: `kuberhealthy/kuberhealthy:v2.7.1` Installed with Helm chart version 90

**Additional context**
It would be nice to not mark it as faulty as the test is successful, but the pod is not terminated correctly. I was expecting it to succeed.

**Comment by koalalorenzo** [comment]
I don't think it is related to #526 but if Kuberhealthy supported Istio it would have probably worked, as the pod is NotReady because of no way for Istio to know if the main container is working or not.

Nonetheless, I am expecting the report to be successful, as the test inside the Kuberhealthy container is successful!

**Comment by integrii** [comment]
Did you ever figure this one out @koalalorenzo ?  I actually can't think of what would case this.  If the pod connected successfully, and was able to report to Kuberhealthy, then the `khstate` resource should reflect the new passing state...
