### ISSUE TITLE
PodDisruptionBudgets API version policy/v1beta1 removed in Kubernetes 1.25

### ISSUE THREAD

**Issue by seifrajhi** [kuberhealthy/kuberhealthy#1143]
**Describe the bug**
I was trying to install kuberhealthy  in my kubernetes cluster version 1.25, but I faced issue with `kind: PodDisruptionBudget` since in version v1.25  PodDisruptionBudgets API version policy/v1beta1 removed.

**Steps To Reproduce**
```
# If you don't use Prometheus:
kubectl create namespace kuberhealthy
kubectl apply -f https://raw.githubusercontent.com/kuberhealthy/kuberhealthy/master/deploy/kuberhealthy.yaml
```

Can you please add support to the latest version of kubernetes cluster v1.25 of `PodDisruptionBudget`

**Comment by mikeinton** [comment]
Hi @seifrajhi the static yaml files still need to be updated to account for the deprecation of policy/v1beta1.

The remaining components should install without issue and you should have a functional Kuberhealthy in your K8s cluster.

**Comment by seifrajhi** [comment]
avoid stale

**Comment by seifrajhi** [comment]
avoid stale

**Comment by cindyytong** [comment]
@seifrajhi curious if you were able to get this working with v1.25/ if the team addressed your issue?

**Comment by integrii** [comment]
This should actually be working in the latest versions.  I see the proper version in the helm chart's PDB.  Maybe you are using an old version of the chart?

Current PDB template: https://github.com/kuberhealthy/kuberhealthy/blob/master/deploy/helm/kuberhealthy/templates/poddisruptionbudget.yaml
