### ISSUE TITLE
Abandoned Project ?

### ISSUE THREAD

**Issue by djsly** [kuberhealthy/kuberhealthy#1144]
@integrii @joshulyne @jonnydawg
Can you confirm is this project is dead and you don't expect to be contributing and keeping it a CNCF project ?

**Comment by integrii** [comment]
I would like to refresh this project and keep it going. I think a good weekend of focus would bring it up to date. I've been the sole maintainer for some time and life has kept me pretty busy (4 kids).  I think @jonnydawg also may be interested in contributing again. We had a conversation about that this week.

**Comment by jonnydawg** [comment]
I have been looking into putting some time into this project and will start reviving this project soon.

**Comment by djsly** [comment]
thanks @integrii  and @jonnydawg , the main issue we are having is that out security team are forcing us to remove kuberhealthy from our cluster due to the high amount of vulnerabilities. 

If this could be the primary focus , it would help us selling it internally.

**Comment by eddie-knight** [comment]
Hey folks, I put some notes into #1145 that may be a good jumpstart, considering that it's a chance to work toward a shared set of goals alongside other CNCF projects.

The process is [statistically proven](https://www.sonatype.com/state-of-the-software-supply-chain/open-source-security-practices) to reduce the likeliness of new vulnerabilities being found in the project, and you might even consider using the prizes as incentive for bringing new/returning contributors (prizes are up to $500 + swag for each project).

**Comment by ewassef** [comment]
@integrii  @joshulyne  @jonnydawg 
Yall are listed as the CODEOWNERS for the project. We really need some movement on this project in terms of security patches and bug fixes. I am more than happy to join the effort and move things along if you'd like. I feel that not having a release in a year is signaling to the users that the project is dead. 
The architecture is solid, and the product is great but needs some maintenance. Are you open to adding maintainers? If so, i would like to help. I can rekindle the community calls and work on these issues as well as recruit more help. 

Pls let me know at your earliest convenience as we are in a spot where we may seek alternatives and i personally don't want that.

**Comment by integrii** [comment]
Hey Eddie.  I definitely don't want Kuberhealthy to be considered a dead project. I did recently merge a ton of things, upgrade all the deps, and start hacking all that into a big release, but I was also very busy at my day job and that took me away from things (we just had one of the largest launches in gaming history). My job is very clear that outside projects can not be seen as a distraction from your productivity.

As an additional reason for delay, I lost someone close to me a couple years ago and it made my life much harder for a good year and a half.

The branch I was hacking in is `cleanup`. I want to bring the code up to a good working and refreshed state, retest with the latest version of Kubernetes, and do a big release.

I have been unable to find much help with the project. I believe @joshulyne has moved on and @jonnydawg has been idle for a long time. We all used to be at the same employer but now we're all at different employers, so collaboration has been difficult as well. 

I think the big thing right now is to get this cleanup branch shipped so all the dependencies and newly merged things working again. After that, we can start to do more incremental improvements and feature additions. 

I'm in LA this week traveling with my family, but before the end of the year I should have enough time off to get a big new version shipped. Before that happens, I think getting the community meetings going again would help a lot. Perhaps we could all sync up there and talk about moving the project forward again?

What timezone are you in? What time of day works best? What cadence sounds appropriate? If anyone else feels able to contribute, please leave a comment!  I will setup a new zoom call depending on what I hear back here.

**Comment by ewassef** [comment]
Thanks for getting back @integrii.  I'm in the central timezone. So we can definitely catch up.  
Yall created a great product that lots of folks are really excited about so I'm glad you still want to keep it going.  I'll help wherever you need. Let's do it!

**Comment by ewassef** [comment]
@integrii I dont know of a better way to get in touch. but lmk when we can sync up

**Comment by jonwinton** [comment]
@integrii @joshulyne @jonnydawg we reached out a bit in the #kuberhealthy channel in the Kubernetes slack, any chance one of y'all is available to help us figure out how to begin contributing more?

**Comment by integrii** [comment]
Hey Jon! I am excited to have your interest in the project. I checked the Kuberhealthy channel but don't see you in there.  I invited someone with your same name to the channel. Hopefully that is you and we can connect.

**Comment by jonwinton** [comment]
👋 Circling back to this issue to confirm that a number of us are meeting and restarting community meetings/maintenance on this project. If anyone runs across this issue in the future and is interested in participating, [the details for how to join the community Zoom calls can be found in the README](https://github.com/kuberhealthy/kuberhealthy?#monthly-community-meeting).

I'm going to close this issue and will hope to see people in the meetings!
