### ISSUE TITLE
Build a up-to-date deployment-check image

### ISSUE THREAD

**Issue by michaelbanzato** [kuberhealthy/kuberhealthy#1193]
**Describe the solution you would like to see happen**
I would like a new version of deployment-check image, with latest and v1.9.2 tag, if possible.

**Additional context**
The latest image was built Mar 22, 2022.
However this code was update in Aug 16, 2022.
https://github.com/kuberhealthy/kuberhealthy/blob/master/cmd/deployment-check/main.go
Therefore the latest image is not up-to-date.

**Comment by michaelbanzato** [comment]
@integrii are you able to do it? I saw the latest was made by you. 
Thank you.

**Comment by integrii** [comment]
Hey Michael.  We have an RC out right now that we could use help testing.  Check it out here: https://github.com/kuberhealthy/kuberhealthy/releases/tag/v2.8.0-rc2

This RC has a ton of fixes, a whole new updated set of go modules, and several new features.
