### ISSUE TITLE
Implement renovate

### ISSUE THREAD

**Issue by integrii** [kuberhealthy/kuberhealthy#1230]
docs: https://docs.renovatebot.com/

**Comment by sheikhrachel** [comment]
I've opened https://github.com/kuberhealthy/kuberhealthy/pull/1234 to introduce the configuration files.

I believe I need some help permissions-wise in the repo.  I need the ability to configure the Renovate Github App in order for this config to be picked up and watched against.  I've included screenshots of what I see in Kuberhealthy vs what I get in my repos where I've set Renovate up:

![Image](https://github.com/kuberhealthy/kuberhealthy/assets/5142793/25b7fb05-442e-4ce4-bece-bc244267906c)

![Image](https://github.com/kuberhealthy/kuberhealthy/assets/5142793/f9dcea06-af88-459b-be0e-656e10e0795a)
