### ISSUE TITLE
Use semantic versioning for helm chart

### ISSUE THREAD

**Issue by patrikulus** [kuberhealthy/kuberhealthy#1239]
**Describe the solution you would like to see happen**
I would like the kuberhealthy helm chart to use semantic versioning.

**How do you propose we build it?**
A change in the release pipeline config

**Additional context**
This has been already done in the past, however for some reason it has been droped. For now it's confusing to check which version of the chart contains which version of kuberhealthy. Since this chart contains a single product, it could follow the kuberhealthy versions.
![image](https://github.com/kuberhealthy/kuberhealthy/assets/9091483/85389adf-f72e-4d5a-9bd0-1c0ecd4c44ba)

**Comment by integrii** [comment]
This isn't a bad idea, but the helm chart is published programmatically, and moving to semver would mean someone reviewing the cart to ensure the next proper semver version was chosen based on the changes.  Right now, that's not happening, so I think we need to have that become a possibility before we move to a semver version...
