### ISSUE TITLE
Add the support to pass in pod/deployment labels for Kuberhealthy in the Helm Chart

### ISSUE THREAD

**Issue by nonoswz** [kuberhealthy/kuberhealthy#1245]
**Describe the feature you would like and why you want it**

[The current Helm Chart](https://github.com/kuberhealthy/kuberhealthy/blob/master/deploy/helm/kuberhealthy/templates/deployment.yaml#L27-L28) does not allow to pass in labels to the Kuberhealthy pods/deployment, it only set the following label for both pods/deployment spec:

```
      labels:
        app: {{ template "kuberhealthy.name" . }}
```

To use Unified Service Tagging for Kuberhealthy in Datadog, we need to pass in [specific Datadog labels](https://docs.datadoghq.com/getting_started/tagging/unified_service_tagging/?tab=kubernetes) to our Deployments and Pods. 
So I'd like to get the possibility to pass in labels via the `values.yaml` for both Deployment and Pods labels. 

Thanks!

**Comment by sheikhrachel** [comment]
Hi @nonoswz, this should be implemented now under `deployment.customLabels` and `pod.customLabels`.  Let us know if that's sufficient to close this out, or if you're good to go!

**Comment by nonoswz** [comment]
Hi @sheikhrachel! 

Thanks a lot, that's perfect, exactly what I needed! Thanks for the reactivity, it's much appreciated!
