### ISSUE TITLE
Kuberhealthy image v2.8.0-rc3 is not in dockerhub

### ISSUE THREAD

**Issue by JoseAlvarezSonos** [kuberhealthy/kuberhealthy#1263]
**Describe the bug**

According to the latest version of Kuberhealthy Helm chart (105), the latest [app version is v2.8.0-rc3](https://github.com/kuberhealthy/kuberhealthy/blob/fd98e5ae6ef2d159bbb82c9b9efbeec2be52aea5/deploy/helm/kuberhealthy/Chart.yaml#L3). But when looking in [DockerHub for that version](https://hub.docker.com/r/kuberhealthy/kuberhealthy/tags?page=&page_size=&ordering=&name=v2.8.0) it doesn't exists. I double checked in other registries like quay in case it existed somewhere else but I think Kuberhealthy only uses dockerhub.

**Steps To Reproduce**
Deploy the latest helm chart and it will fail due to image not found.

**Expected behavior**
That v2.8.0-rc3 exists in Dockerhub.

**Versions**
 - Kuberhealthy Helm Chart version 105
 - Kuberhealthy app version v2.8.0-rc3

**Comment by oestoer** [comment]
In my values file, I pinned the previous RC `image.tag: v2.8.0-rc2` as a workaround.

Based on this workflow https://github.com/kuberhealthy/kuberhealthy/blob/master/.github/workflows/release.yml, it seems only a `v2.8.0-rc3` tag would need to be added to the repo and this would create the missing docker image
