### ISSUE TITLE
v2.8.0-rc3  Missing from Docker Hub

### ISSUE THREAD

**Issue by sarg3nt** [kuberhealthy/kuberhealthy#1277]
Just an FYI that v2.8.0-rc3  is not on Dockerhub.

**Comment by guillaumebernard84** [comment]
Same problem here when trying to use the latest helm chart (version 105)

**Comment by integrii** [comment]
I hadn't pushed it up yet.  I only tagged and pushed `v2.8.0-rc3`, which is in the tags list. Where did you get that image tag from?

I assume you saw this from a file or something like that?

Sorry for being behind with project maintenance.

**Comment by guillaumebernard84** [comment]
Hello, it's in the helm chart version 105

**Comment by MohanSha** [comment]
@integrii, the issue still exists, it is not available in docker hub. it's in the helm chart version 105. 
<img width="1720" alt="Screenshot 2024-11-27 at 3 44 52 PM" src="https://github.com/user-attachments/assets/99f94639-94c8-4239-ad6d-a1553127508a">
