### ISSUE TITLE
'helm search repo' returns RC versions without the `--devel` flag

### ISSUE THREAD

**Issue by sarg3nt** [kuberhealthy/kuberhealthy#1278]
When doing a `helm search repo` we are getting version 105 back, which is a release candidate.
We should not when not passing the `--devel` flag

**Comment by integrii** [comment]
Interesting. [This](https://github.com/kuberhealthy/kuberhealthy/blob/master/.github/workflows/helm-repo-update.yml) is the helm repo update github action. Any ideas?
