### ISSUE TITLE
Provide ARM64 images

### ISSUE THREAD

**Issue by everflux** [kuberhealthy/kuberhealthy#166]
**Describe the feature you would like and why you want it**
It would be great, if kuberhealthy could be used for ARM64 based clusters. A multi-arch manifest/image is the only thing required to support that use case imho.

**Comment by integrii** [comment]
Excellent idea!  I don't think we ever realized that there is a common use case for arm here.  It should be quick to get this added, built, and tagged.

**Comment by weikinhuang** [comment]
any update on this?

**Comment by integrii** [comment]
We haven't done this yet, but it seems that with the launch of Kuberhealthy 2, this has become harder.   KH2 comes with several different containers - one for each check - that get spawned from the main kuberhealthy instance.  

This means that all checks as well as the main kuberhealthy would need compiled with arm and x86_64...

**Comment by integrii** [comment]
Is this how you do multi-arch images still: https://engineering.docker.com/2019/04/multi-arch-images/ ?

**Comment by integrii** [comment]
Looks like we need to find out if Quay.io supports multi-arch images as well.

**Comment by DerrickMartinez** [comment]
Looking forward to arm64 support
