### ISSUE TITLE
Create Kuberhealthy Alerting System

### ISSUE THREAD

**Issue by integrii** [kuberhealthy/kuberhealthy#597]
We should have an app that scrapes Kuberhealthy and sends alerts to a variety of endpoints.  Currently the only way to get alerts is to scrape the JSON status page or implement your own prometheus alertmanager configuration.

**Comment by integrii** [comment]
Not sure this is in scope for the project given that prom has alert management, but I am leaving it open as a proposal.

**Comment by aantn** [comment]
@integrii would an integration with Robusta (https://github.com/robusta-dev/robusta) be a viable option here?

I'm part of the Robusta team and we'd be happy to have an integration

**Comment by integrii** [comment]
That sounds really interesting!  Many of the checks I see on your GitHub project page seem like they could be used as Kuberhealthy checks.

You should be able to integrate with the JSON status page pretty easily.  That page is the default page served by the `kuberhealthy` pods.   It looks like [this](https://github.com/kuberhealthy/kuberhealthy#status-page).

Writing your own check is also [pretty easy if you haven't seen it yet](https://github.com/kuberhealthy/kuberhealthy/blob/master/docs/CHECK_CREATION.md)!
