### ISSUE TITLE
Implement test baseline

### ISSUE THREAD

**Issue by lolimjake** [kuberhealthy/kuberhealthy#6]
For first pass we should shoot for full unit test coverage.

**Comment by joshulyne** [comment]
@integrii do our implemented e2e tests cover this issue?

**Comment by integrii** [comment]
I believe our e2e tests help a lot, but the 'test baseline' described here directly references code coverage, which entails smaller unit and function tests...

I think we can call this one 'complete' when we have some sense of code coverage and are testing at least ~50% of our code.
