### ISSUE TITLE
khjob once to multiple run

### ISSUE THREAD

**Issue by yinhongzhao6688** [kuberhealthy/kuberhealthy#806]
Is it possible to manage the khjob's once or multiple runner by the annotation 's the key and
 the value .
In cluster management, periodic collection and once collection are both necessary,when problems are encountered.

**Comment by integrii** [comment]
Can you explain this a little more?  Would you like something like `completions` or `parallelism` on a `khjob` resource?

**Comment by yinhongzhao6688** [comment]
The main intention is to perform one-time tasks as needed. When khjob is deployed, the khjob’s key in annotation is true. This time it will be executed immediately. After the execution is completed, the khjob’s key in annotation  is false. If I need to execute it next time, I will update the annotation's key. : True; scheduling can be executed immediately;
