### ISSUE TITLE
Move Docker images to an alternative registry to avoid hitting Docker Hub rate limits

### ISSUE THREAD

**Issue by RomanSharapov** [kuberhealthy/kuberhealthy#851]
**Describe the solution you would like to see happen**
As described [here](https://www.docker.com/increase-rate-limits), Docker has enabled download rate limits for pull requests on Docker Hub which may resolve in failures upon Kuberhealthy or Checker Pods images download. By default, the Kuberhealthy Helm Chart is using DockerHub as the default repository for the images.

**How do you propose we build it?**
All images should be migrated to an alternative registry like [Quay.io](https://quay.io/), [GCR](https://cloud.google.com/container-registry), or similar and the Helm chart should include this registry by default for all images.

**Comment by integrii** [comment]
FWIW, we used to host on Quay.io.  They had a lot of random downtime, so we moved to docker.  GCR could be possible, but I think it costs money to host there?  I like this proposal.
