### ISSUE TITLE
jobCleanupDuration and maxCheckPods are not properly respected

### ISSUE THREAD

**Issue by AshutoshNirkhe** [kuberhealthy/kuberhealthy#859]
**Describe the bug**
Currently Kuberhealthy (reaper part) doesn't seem to be properly working. It does reap the pods but seems like lowering the values of  jobCleanupDuration and maxCheckPods configs doesn't really help much.

**Steps To Reproduce**
- Set below values either through values.yaml or just edit the kuberhealthy configmap,
    jobCleanupDuration: 3m
    maxCheckPods: 1
- Optionally restart Kuberhealthy pods to make sure they pick up the changes.

We still see at least 2 pods of each checker whatsoever tweaks I make to those 2 values,

$  kubectl get pods -n synthetic
NAME                             READY   STATUS      RESTARTS   AGE
deployment-1614851948            0/1     Completed   0          94m
deployment-1614855548            0/1     Completed   0          34m
dns-status-internal-1614857048   0/1     Completed   0          9m11s
dns-status-internal-1614857348   0/1     Completed   0          4m11s
kuberhealthy-9d594c6f5-hrf5b     1/1     Running     0          4h35m
kuberhealthy-9d594c6f5-khxxd     1/1     Running     0          4h36m

**Expected behavior**
We would ideally like to get rid off all 0/1 Completed pods to be reaped as much quickly as possible to free up IPs. But at least if we could lower this down to 1 pod per check, it will be really awesome!
PS, I tried with jobCleanupDuration=1m and maxCheckPods=0 , but it didn't help.

**Screenshots**
If applicable, add screenshots to help explain your problem.  You can paste images into github and they will upload automatically.

**Versions**
 - Kubernetes Version: 1.18.14
 - Kuberhealthy Release v2.4.0

**Additional context**

**Comment by AshutoshNirkhe** [comment]
Ok, small correction. It does work at first and then sometimes (may be its something to do with repaer logic frequency of checking) but the point is it keeps the Completed pods hanging around which doesn't really add any value but keeps using IPs,

Settings -
    jobCleanupDuration: 1m
    maxCheckPods: 0

$  kubectl get pods -n synthetic
NAME                             READY   STATUS      RESTARTS   AGE
deployment-1614859236            0/1     Completed   0          12m
deployment-1614859836            0/1     Completed   0          2m15s
dns-status-internal-1614859836   0/1     Completed   0          2m15s
kuberhealthy-69ff96ff5c-gk659    1/1     Running     1          4d21h
kuberhealthy-69ff96ff5c-xf5xj    1/1     Running     0          4d21h

See the 1st deployment pod is 12m older, but still didn't get reaped off.

**Comment by integrii** [comment]
Interesting.  Can you kill the Kuberhealthy pod, then start it and look for [these log lines](https://github.com/Comcast/kuberhealthy/blob/e71071039e84cedf5441b83afe2343c6a4383216/cmd/kuberhealthy/reaper.go#L51-L53
):

```
	log.Infoln("checkReaper: starting up...")
	log.Infoln("checkReaper: job cleanup duration:", cfg.JobCleanupDuration)
	log.Infoln("checkReaper: max checker pods:", cfg.MaxCheckPods)
```

That would confirm what options the pod is seeing.  Note that these are now in the main Kuberhealthy binary as of the latest release and that the check-reaper running as a standalone cron-job is now deprecated.

**Comment by joshulyne** [comment]
@AshutoshNirkhe Fixed in #862! Feel free to test with `kuberhealthy/kuberhealthy:v2.4.1`

**Comment by AshutoshNirkhe** [comment]
> @AshutoshNirkhe Fixed in #862! Feel free to test with `kuberhealthy/kuberhealthy:v2.4.1`

Thanks a lot @joshulyne

**Comment by AshutoshNirkhe** [comment]
@joshulyne @integrii I don't think the issue is fixed yet unfortunately. I have deployed v2.4.1 in my test k8s cluster now. But I still see 4-5 pods of each checker running. Please find attached all the details.

[Kuberhealthy-settings-logs.txt](https://github.com/Comcast/kuberhealthy/files/6336730/Kuberhealthy-settings-logs.txt)

Basically I don't get why it always checks that there are more than '4' pods in Completed stage even when I am setting maxCheckPods to 0 here. And then it only deletes one (probably oldest of all). 
checkReaper: Found more than 4 checker pods with the same name in status `Succeeded` that were created more recently. Deleting pod: image-pull-check-1618837982

So it kind of allows to grow till at east 4 checker pods of each check and then keeps reaping the oldest one periodically, leaving 4-5 pods behind always. Can you please check and help me correct in case am misconfiguring the things. Thanks!

**Comment by joshulyne** [comment]
@AshutoshNirkhe So we don't allow for `maxCheckPods: 0` because we assume folks want at least one checker pod around for troubleshooting purposes -- we could definitely add better logging or error handling for this so folks know that 0 isn't allowed and that we default to 4 if thats the case. Is there a reason you wanted that to be 0? Changing it to 1 should do the trick.

**Comment by AshutoshNirkhe** [comment]
> @AshutoshNirkhe So we don't allow for `maxCheckPods: 0` because we assume folks want at least one checker pod around for troubleshooting purposes -- we could definitely add better logging or error handling for this so folks know that 0 isn't allowed and that we default to 4 if thats the case. Is there a reason you wanted that to be 0? Changing it to 1 should do the trick.

I see, I had tried that on v2.4.0 but not this time. Now I set maxCheckPods to 1 and its leaving behind 2 pods per check, which looks expected as per v2.4.1. We would have been more happy if if we could get it to only 1 checker pod lying in Completed state, but this is still much better. Thanks for checking!

`
$ kubectl get pods -n synthetic
NAME                             READY   STATUS      RESTARTS   AGE
deployment-1618888429            0/1     Completed   0          13m
deployment-1618889029            0/1     Completed   0          3m19s
dns-status-internal-1618888729   0/1     Completed   0          8m19s
dns-status-internal-1618889029   0/1     Completed   0          3m19s
kuberhealthy-9d49c5745-fgjws     1/1     Running     0          11h
kuberhealthy-9d49c5745-lfh4g     1/1     Running     0          11h

`

**Comment by djsly** [comment]
Why are we getting 2 competed if set to 1 ?

To us a completed job doesn’t need to stay around since it pass, the faulty ones are the one we would like to keep the last failed around. 

In AKS, each pods takes up an IP on the subnet and with many checks we often end up paying for a full. NOde where only compared jobs are assigned (taking all IPs foe that node). 

Sylvain.

**Comment by joshulyne** [comment]
@AshutoshNirkhe @djsly looking at the reaper logic, in terms of completed pods lying around, it seems like its always been maxCheckPods + 1  and since we don't allow for 0 maxCheckerPods (has to be at least be 1), resulting in always 2 lying around... we should address this so it makes more sense to the user and also allow users to choose to only have one completed pod lying around at most -- reopening this and working on a PR for it!
