### ISSUE TITLE
Propagate extraLabels to the metrics for that check

### ISSUE THREAD

**Issue by talonx** [kuberhealthy/kuberhealthy#922]
**Describe the feature you would like and why you want it**
The labels in `extraLabels` should ideally get propagated as labels to the Prometheus metrics associated with that check.

E.g. if extraLabels looks like
```
  extraLabels:
    service: store
```
the `kuberhealthy_check` should have the label `service: store`

**Additional context**
This adds additional and required context to the metric and helps us simplify the deployment of tests.

**Comment by joshulyne** [comment]
Ahh that makes sense. It is possible, but I do believe it will require an additional kube api call to get the extra labels information from the khcheck pod when we generate the metric. @integrii thoughts?

**Comment by integrii** [comment]
I am not against it... We could probably fetch the labels off the `podSpec` and `extraLabels` fields from the `khcheck` or `khjob` that created the pod.
