### ISSUE TITLE
Checks are getting scheduled at nearly the same time.

### ISSUE THREAD

**Issue by jonnydawg** [kuberhealthy/kuberhealthy#925]
**Describe the bug**
A KHC will get scheduled twice -- one after the other within milliseconds:
![image](https://user-images.githubusercontent.com/12464614/117706304-fe489800-b181-11eb-87cb-b7a191975c7c.png)
![image](https://user-images.githubusercontent.com/12464614/117706348-0a345a00-b182-11eb-804a-7d39054a2b04.png)
![image](https://user-images.githubusercontent.com/12464614/117706384-128c9500-b182-11eb-8a99-6fc7f83e2054.png)

This always forces the one that is scheduled first to fail / error due to an invalid check uuid resulting in a rejection from the Kuberhealthy master and a `400 Bad Request` from the checker pod.

**Steps To Reproduce**
- Run a deployment of kuberhealthy with `latest` tag
- That container's digest for reference: `sha256:e03e18490bd87e162d2c3a51a7f7f8c6bdd1a883af90b0a7e9a6ea4ef40d1c42` (Today is May 10, 2021)

**Expected behavior**
Normal Kuberhealthy check lifecycle (single checker pod -> check -> report) 

**Versions**
 - Kubernetes Version: 1.11.7

**Comment by integrii** [comment]
@joshulyne has made progress on this one.
