### ISSUE TITLE
Refactor comcast -> kuberhealthy did not update index.yaml properly, .tgz downloads status code 404

### ISSUE THREAD

**Issue by xenoglaux88** [kuberhealthy/kuberhealthy#938]
**Describe the bug**
The index.yaml did not refactor all the source links of `comcast.github.io` -> `kuberhealthy.github.io`. As a result, installs are now falling. Because the pointers for the `.tgz` are pointing to the old url and are returning status 404 codes.

**Steps To Reproduce**
```
    kubectl create namespace kuberhealthy
    kubectl config set-context --current --namespace=kuberhealthy
    helm repo add kuberhealthy https://kuberhealthy.github.io/kuberhealthy/helm-repos
    helm install kuberhealthy kuberhealthy/kuberhealthy

```
The install step is the where the problem shows up.

**Expected behavior**
I expect the `.tgz` to return 200 status and download.

**Screenshots**
```
helm install kuberhealthy kuberhealthy/kuberhealthy --debug
install.go:173: [debug] Original chart version: ""
Error: failed to fetch https://comcast.github.io/kuberhealthy/helm-repos/archives/kuberhealthy-64.tgz : 404 Not Found
helm.go:81: [debug] failed to fetch https://comcast.github.io/kuberhealthy/helm-repos/archives/kuberhealthy-64.tgz : 404 Not Found
```

**Versions**
 - Cluster OS: EKS
 - Kubernetes Version: 1.19
 - 64

**Additional context**
I also tried `helm update` and it didn't solve the issue.

**Comment by djsly** [comment]
This is breaking our deployment pipelines since the helm provider in terraform fails when trying to reach the chart repo. 

Hopefully, this is getting looked at !

**Comment by xenoglaux88** [comment]
Yea, I was deploying some terraform stuff when I ran into this. I hope so too!

**Comment by blame19** [comment]
Ditto. Changing the url as @xenoglaux88 suggested solved the issue, I was able to install a custom version of the chart (over https://github.com/blame19/kuberhealthy) in my cluster.

I might open a PR, but I'd rather have someone from Comcast have a look at this - not sure what is required in terms of versioning :)

**Comment by xenoglaux88** [comment]
> This is breaking our deployment pipelines since the helm provider in terraform fails when trying to reach the chart repo.
> 
> Hopefully, this is getting looked at !

I've created another  [ticket](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1352) in terraform-aws-eks repo as well to address the terraform issue.

**Comment by integrii** [comment]
Checking this out!  We caught a bunch of things with the rename, but didn't catch this obviously.

**Comment by integrii** [comment]
PR created and should be approved soon... We didn't catch this because it wasn't safe to bulk-rename `comcast.github.io` due to it being in the CRD files...

**Comment by xenoglaux88** [comment]
Awesome! Thank you @integrii

**Comment by integrii** [comment]
You're welcome @xenoglaux88!

You will have to run

```
helm repo remove kuberhealthy
```

before re-running the repo add/install commands:

```
    kubectl create namespace kuberhealthy
    kubectl config set-context --current --namespace=kuberhealthy
    helm repo add kuberhealthy https://kuberhealthy.github.io/kuberhealthy/helm-repos
    helm install kuberhealthy kuberhealthy/kuberhealthy
```

before this works again.


Sorry for the mix up.

**Comment by xenoglaux88** [comment]
All good, been doing this a long time. Used to these landmass changes lol.
