### ISSUE TITLE
Checks fail with "timed out waiting for pod to exit" 

### ISSUE THREAD

**Issue by talonx** [kuberhealthy/kuberhealthy#971]
**Describe the bug**
One of my custom checks keeps failing with "timed out waiting for pod to exit". I can see that the pod for the check comes up and the logs show that the check was able to run correctly.

**Steps To Reproduce**
- Running a custom check. Note that I have around 7 custom checks running and this happens with only one of them.

**Expected behavior**
Check should pass.

**Screenshots**
NA

**Versions**
 - Kubernetes Version: 1.17
 - Env : GKE version 1.17.17-gke.4900
 - Kuberhealthy Release v2.4.0

**Comment by integrii** [comment]
Interesting.  Did the pod fully shut down and transition into `Error` or `Completed` state?  Can you get the logs off the pod after it shuts down with `kubectl logs <podName> --previous`?

**Comment by integrii** [comment]
Could this have to do with #903?  Essentially in that error, pods created in namespaces outside of the Kuberhealthy namespace are automatically deleted.

**Comment by talonx** [comment]
> Interesting. Did the pod fully shut down and transition into `Error` or `Completed` state? Can you get the logs off the pod after it shuts down with `kubectl logs <podName> --previous`?

Thanks. I see the pod is in the Running state even after the pod logs show the test is done and dusted. I suspect this might be a problem with the check's code which leaves non-daemon threads hanging around. I'll check and get back.

**Comment by talonx** [comment]
> Could this have to do with #903? Essentially in that error, pods created in namespaces outside of the Kuberhealthy namespace are automatically deleted.

I don't think so - as we deploy all checks in the kuberhealthy namespace.

**Comment by talonx** [comment]
I checked our code - and it looks like there was a thread pool with non-daemon threads lying around. Shutting it down took care of it. Thank you.
