### ISSUE TITLE
Improve Prometheus metrics documentation

### ISSUE THREAD

**Issue by talonx** [kuberhealthy/kuberhealthy#974]
The documentation on the metrics exposed by KH can be improved. The current doc at https://github.com/kuberhealthy/kuberhealthy/blob/master/docs/K8s-KPIs-with-Kuberhealthy.md does not describe the `kuberhealthy_check` metric in detail. A few lines about when `status=1` will have a value of 0/1 and when `status=0` will be 0/1, or when these labels will be missing in the series would be helpful to create fine grained alert queries in PromQL.

**Comment by integrii** [comment]
Thanks for the report.  This is in the same category as #981 I think.
