### ISSUE TITLE
Negative run durations on the status page

### ISSUE THREAD

**Issue by jonnydawg** [kuberhealthy/kuberhealthy#984]
**Describe the bug**
Kuberhealthy can report negative `RunDurations` to the status page.

Users who use `RunDuration` as a metric can see skewed results in their calculations and reports.

**Steps To Reproduce**
Not sure how to reproduce this yet, but noticed it during a presentation of Kuberhealthy.

**Expected behavior**
The status page should always show non-negative times (not sure what a negative run duration would even mean for a check)

**Screenshots**
![image](https://user-images.githubusercontent.com/12464614/125334794-a56fba00-e300-11eb-9c08-6963836b52ec.png)

**Video timestamp**
https://youtu.be/4w62d0kL7Mw?t=4097

**Versions**
 - Cluster OS: kind default OS
 - Kubernetes Version: 1.22.1
 - Kuberhealthy Release or build: 2.5.0

**Comment by integrii** [comment]
I wonder if this was because KinD was having NTP-like issues...
