### ISSUE TITLE
All Kuberhealthy checks creation failing after installing latest v2.6.0 release

### ISSUE THREAD

**Issue by AshutoshNirkhe** [kuberhealthy/kuberhealthy#988]
**Describe the bug**
After installing latest (v2.6) Kuberhealthy, new crds got installed. But all the khchecks and khstate creation started failing with error,
"invalid: spec.LastRun: Invalid value: \"null\": spec.LastRun in body must be of type string: \"null\""

**Steps To Reproduce**
- Install v2.6 Kuberhealthy
- Enable few upstream checks like deployment, dns-internal etc.

**Expected behavior**
All khcheck pods and khstates should have been created properly.

**Screenshots**
If applicable, add screenshots to help explain your problem.  You can paste images into github and they will upload automatically.

Logs from Kuberhealthy backend pods,
```
time="2021-07-20T15:08:19Z" level=info msg="Starting check: synthetic / dns-status-internal"
time="2021-07-20T15:08:19Z" level=info msg="Running check: dns-status-internal"
time="2021-07-20T15:08:19Z" level=debug msg="Generated new UUID for external check: e1f45822-0d5e-40a2-8420-6228f53eaced"
time="2021-07-20T15:08:19Z" level=info msg="e1f45822-0d5e-40a2-8420-6228f53eaced synthetic/dns-status-internal: [Setting expected UUID to: e1f45822-0d5e-40a2-8420-6228f53ea
ced]"
time="2021-07-20T15:08:19Z" level=info msg="Starting check: synthetic / deployment"
time="2021-07-20T15:08:19Z" level=info msg="Running check: deployment"
time="2021-07-20T15:08:19Z" level=debug msg="Generated new UUID for external check: 689c1ec7-45a0-49a6-9d9c-24300f63ebf6"
time="2021-07-20T15:08:19Z" level=info msg="689c1ec7-45a0-49a6-9d9c-24300f63ebf6 synthetic/deployment: [Setting expected UUID to: 689c1ec7-45a0-49a6-9d9c-24300f63ebf6]"
time="2021-07-20T15:08:20Z" level=info msg="689c1ec7-45a0-49a6-9d9c-24300f63ebf6 synthetic/deployment: [khstate did not exist, so a default object will be created]"
time="2021-07-20T15:08:20Z" level=info msg="689c1ec7-45a0-49a6-9d9c-24300f63ebf6 synthetic/deployment: [Creating khstate deployment synthetic because it did not exist]"
time="2021-07-20T15:08:20Z" level=info msg="e1f45822-0d5e-40a2-8420-6228f53eaced synthetic/dns-status-internal: [khstate did not exist, so a default object will be created]
"
time="2021-07-20T15:08:20Z" level=info msg="e1f45822-0d5e-40a2-8420-6228f53eaced synthetic/dns-status-internal: [Creating khstate dns-status-internal synthetic because it d
id not exist]"
time="2021-07-20T15:08:20Z" level=info msg="e1f45822-0d5e-40a2-8420-6228f53eaced synthetic/dns-status-internal: [failed to create a khstate after finding that it did not ex
ist: KuberhealthyState.comcast.github.io \"dns-status-internal\" is invalid: spec.LastRun: Invalid value: \"null\": spec.LastRun in body must be of type string: \"null\"]"
time="2021-07-20T15:08:20Z" level=error msg="Error running check: dns-status-internal in namespace synthetic: KuberhealthyState.comcast.github.io \"dns-status-internal\" is
 invalid: spec.LastRun: Invalid value: \"null\": spec.LastRun in body must be of type string: \"null\""
time="2021-07-20T15:08:20Z" level=debug msg="Checking existence of custom resource: dns-status-internal"
```

**Versions**
 - Cluster OS: [e.g. CoreOS 1800.1.0]
 - Kubernetes Version: 1.20.7
 - Kuberhealthy Release v2.6.0

**Additional context**
All checks work perfectly fine with v2.5.0 KH release, but fail with v2.6.0 (fresh) installation.
LastRun field seems to be coming from khstate spec, 
https://github.com/kuberhealthy/kuberhealthy/pull/937/files#diff-5e5ae41d19dd83d75f4a16a51db94409dbebeac54e7cd0b9454b84eb1b74741eR38

Another question I have is when I tried upgrading from v2.5.0 to v2.6.0, crds were not updated automatically and hence checks continued to run fine. I guess helm upgrade doesn't handle this. Do we need to remove older crds and install new ones manually before chart upgrade ? How are we supposed to handle existing custom resources (checks/jobs) in such case ?

**Comment by integrii** [comment]
Thanks for the report @AshutoshNirkhe - we will work on reproducing this one.  We haven't seen this in our end to end tests or in our clusters, which is a concern.  @jonnydawg is checking this out.

**Comment by jonnydawg** [comment]
Looks like this might be an issue related to how we generated our CRDs -- leaving this here as a note for later reference:

```
https://github.com/kubernetes/kubernetes/issues/58311
https://github.com/kubernetes/kubernetes/issues/66899
https://github.com/kubernetes/kubernetes/issues/86811
https://github.com/kubernetes/code-generator/tree/master/examples/crd/apis/example/v1
https://github.com/kubernetes-sigs/cluster-api/blob/bf790fc2a53614ff5d3405c83c0de0dd3303bb1f/api/v1alpha2/common_types.go#L46-L67
```

**Comment by integrii** [comment]
This should be fixed in v2.7.0.

**Comment by AshutoshNirkhe** [comment]
> This should be fixed in v2.7.0.

@integrii @jonnydawg Thanks for fixing this. I had one query. Do we need to manually drop older crds and install new ones ?
As such helm upgrade to v2.6/2.7 doesn't really apply new crds.

**Comment by donggangcj** [comment]
@jonnydawg  whether the kuberhealthy state fields `Node` can be null? it seems to be forgotten.

![image](https://user-images.githubusercontent.com/22852751/134326168-f8cfdca9-d174-4657-9bc5-c613fab64dc2.png)

**Comment by Hungrylion2019** [comment]
I met the question for many times. But it's not the  field "LastRun". 
**How I deal with  this question**
