### ISSUE TITLE
Storage check adding securityContext to resources instead of container in template

### ISSUE THREAD

**Issue by mitchellmaler** [kuberhealthy/kuberhealthy#994]
**Describe the bug**
Enabled the storage checker and the chart is failing to deploy:
```
error validating data: ValidationError(KuberhealthyCheck.spec.podSpec.containers[0].resources): unknown field "securityContext" in io.github.comcast.v1.KuberhealthyCheck.spec.podSpec.containers.resource
```

Looks like in the template the securityContext needs to be moved back a tab.
https://github.com/kuberhealthy/kuberhealthy/blob/master/deploy/helm/kuberhealthy/templates/khcheck-storage.yaml#L56

**Steps To Reproduce**
- deploy helm chart with storage check enabled and securityContext enabled

**Expected behavior**
storage check is applied

**Comment by thllxb** [comment]
@integrii when will be next release to include this fix?

**Comment by integrii** [comment]
I pushed a new version of the Helm chart already, so the Helm chart should have your fix!
