### ISSUE TITLE
Kuberhealthy deployed pods should inherit the chart PriorityClass

### ISSUE THREAD

**Issue by blame19** [kuberhealthy/kuberhealthy#997]
**Describe the feature you would like and why you want it**
The kuberhealthy deployment allows us to set a priority class name: 

https://github.com/kuberhealthy/kuberhealthy/blob/a507103e313b888f8a503bc4570295bb4efeebde/deploy/helm/kuberhealthy/values.yaml#L80

This work as expected, however, kuberhealthy will deploy a number of other pods to run its checks. We would like a way for those pods to inherit the setting and share the same priorityclassname.

**Comment by integrii** [comment]
Hey there.

If you want your checker pods to run at a higher `priorityClassName`, just configure it on the `khcheck` spec.  The `khcheck` spec will pass through to the checker pods and result in your `priorityClassName` taking effect on them.

Setting the `priorityClassName` on the Helm chart only changes the priority on the actual Kuberhealthy pods - not the checker pods running under it.  Those are configured by `khcheck` resources.

**Comment by blame19** [comment]
You're right. Thanks for clarifying this for me, @integrii
